import os
import re
import random
import string
import time

class Solution:
    def solve(self, resources_path: str) -> dict:
        grammar_keywords = set()
        grammar_literals = set()
        try:
            grammar_path = os.path.join(resources_path, "sql_grammar.txt")
            with open(grammar_path, "r", encoding="utf-8", errors="ignore") as f:
                gtext = f.read()
            for tok in re.findall(r"\b[A-Z][A-Z0-9_]*\b", gtext):
                grammar_keywords.add(tok)
            for tok in re.findall(r"'([^']*)'", gtext):
                if tok:
                    grammar_literals.add(tok)
            for tok in re.findall(r'"([^"]*)"', gtext):
                if tok:
                    grammar_literals.add(tok)
        except Exception:
            pass

        kw_list = sorted(grammar_keywords)
        lit_list = sorted(grammar_literals)

        code_lines = []
        code_lines.append("import random, re, string, time")
        code_lines.append("RUN_DONE = False")
        code_lines.append("GRAMMAR_KEYWORDS = set({})".format(repr(kw_list)))
        code_lines.append("GRAMMAR_LITERALS = set({})".format(repr(lit_list)))
        code_lines.append("")
        code_lines.append("def fuzz(parse_sql):")
        code_lines.append("    global RUN_DONE")
        code_lines.append("    if RUN_DONE:")
        code_lines.append("        return False")
        code_lines.append("    rnd = random.Random()")
        code_lines.append("    rnd.seed(int(time.time() * 1000) ^ 0x9E3779B97F4A7C15)")
        code_lines.append("")
        code_lines.append("    # Pools of identifiers and constants")
        code_lines.append("    base_tables = ['t','users','orders','products','logs','data','info','alpha','beta','gamma','a','b','c','m','n','x','y','z']")
        code_lines.append("    base_tables += [f't{i}' for i in range(20)]")
        code_lines.append("    base_cols = ['id','user_id','order_id','product_id','name','email','address','city','state','zip','price','qty','quantity','amount','total','flag','active','enabled','status','score','rating','ts','timestamp','created_at','updated_at','x','y','z','a','b','c']")
        code_lines.append("    base_cols += [f'col{i}' for i in range(1, 41)]")
        code_lines.append("    # merge grammar keywords to enrich identifier/domain if any")
        code_lines.append("    extra_kw = [k.lower() for k in list(GRAMMAR_KEYWORDS) if k and k.isalpha() and k.isupper() and len(k) > 1]")
        code_lines.append("    base_tables += [k.lower() for k in extra_kw[:30]]")
        code_lines.append("    base_cols += [k.lower() for k in extra_kw[30:80]]")
        code_lines.append("")
        code_lines.append("    numeric_constants = ['0','1','-1','42','-42','2147483647','-2147483648','9223372036854775807','-9223372036854775808','3.14159','-0.0','0.0001','1e10','-2E-3','+4.','.5','+.5','-.5','1.','1.0e+2','6.02E23','0xFF','0xabcdef','0b101010','00','007','08']")
        code_lines.append("    string_constants = [")
        code_lines.append("        \"''\",\"'a'\",\"'abc'\",\"'A B C'\",\"'123'\",\"'NULL'\",\"'O''Reilly'\",")
        code_lines.append("        \"'line1\\nline2'\",\"'tab\\tchar'\",\"'quote\\''\",\"'\\\\backslash'\",\"'semi;colon'\",")
        code_lines.append("        \"E'escape'\",\"N'national'\",\"x'ABCD'\",\"X'00FF'\"")
        code_lines.append("    ]")
        code_lines.append("    bool_null = ['TRUE','FALSE','NULL']")
        code_lines.append("")
        code_lines.append("    # SQL tokens and operators")
        code_lines.append("    comparison_ops = ['=','<>','!=','<','>','<=','>=','IS','IS NOT','IN','NOT IN','LIKE','NOT LIKE','GLOB','REGEXP','MATCH','==']")
        code_lines.append("    arithmetic_ops = ['+','-','*','/','%','||','&','|','^','<<','>>']")
        code_lines.append("    logical_ops = ['AND','OR']")
        code_lines.append("")
        code_lines.append("    join_types = [")
        code_lines.append("        'JOIN','INNER JOIN','LEFT JOIN','LEFT OUTER JOIN','RIGHT JOIN','RIGHT OUTER JOIN','FULL JOIN','FULL OUTER JOIN','CROSS JOIN','NATURAL JOIN','NATURAL LEFT JOIN'")
        code_lines.append("    ]")
        code_lines.append("")
        code_lines.append("    sql_types = [")
        code_lines.append("        'INT','INTEGER','SMALLINT','BIGINT','TINYINT','DECIMAL(10,2)','NUMERIC(18,4)','REAL','DOUBLE','FLOAT',")
        code_lines.append("        'CHAR(10)','VARCHAR(255)','TEXT','CLOB','BLOB','BOOLEAN','DATE','TIME','TIMESTAMP','DATETIME'")
        code_lines.append("    ]")
        code_lines.append("    constraints_kw = ['PRIMARY KEY','NOT NULL','UNIQUE','CHECK','DEFAULT','REFERENCES']")
        code_lines.append("")
        code_lines.append("    func_names = [")
        code_lines.append("        'ABS','RANDOM','ROUND','FLOOR','CEIL','CEILING','POWER','SQRT','EXP','LOG','LOG10','SIN','COS','TAN','ASIN','ACOS','ATAN',")
        code_lines.append("        'UPPER','LOWER','LENGTH','SUBSTR','SUBSTRING','TRIM','LTRIM','RTRIM','REPLACE','COALESCE','IFNULL','NULLIF',")
        code_lines.append("        'COUNT','SUM','AVG','MIN','MAX','GROUP_CONCAT', 'PRINTF'")
        code_lines.append("    ]")
        code_lines.append("    # Add extra function-like keywords from grammar to widen coverage")
        code_lines.append("    func_names += [k for k in list(GRAMMAR_KEYWORDS) if k.isalpha() and k.isupper() and len(k) > 2][:40]")
        code_lines.append("")
        code_lines.append("    def maybe(p):")
        code_lines.append("        return rnd.random() < p")
        code_lines.append("")
        code_lines.append("    def mix_case(tok):")
        code_lines.append("        r = rnd.random()")
        code_lines.append("        if r < 0.5:")
        code_lines.append("            return tok")
        code_lines.append("        elif r < 0.7:")
        code_lines.append("            return tok.lower()")
        code_lines.append("        elif r < 0.9:")
        code_lines.append("            return tok.upper()")
        code_lines.append("        else:")
        code_lines.append("            # random per-char case")
        code_lines.append("            out = []")
        code_lines.append("            for ch in tok:")
        code_lines.append("                if ch.isalpha():")
        code_lines.append("                    out.append(ch.upper() if rnd.random() < 0.5 else ch.lower())")
        code_lines.append("                else:")
        code_lines.append("                    out.append(ch)")
        code_lines.append("            return ''.join(out)")
        code_lines.append("")
        code_lines.append("    def rand_ident_base():")
        code_lines.append("        # May include keywords to force quoting")
        code_lines.append("        pool = base_cols + base_tables")
        code_lines.append("        if maybe(0.2) and GRAMMAR_KEYWORDS:")
        code_lines.append("            pool += [k.lower() for k in list(GRAMMAR_KEYWORDS)[:50]]")
        code_lines.append("        name = rnd.choice(pool)")
        code_lines.append("        if maybe(0.3):")
        code_lines.append("            # invent new")
        code_lines.append("            letters = string.ascii_lowercase + '_'")
        code_lines.append("            length = rnd.randint(1, 12)")
        code_lines.append("            name = ''.join(rnd.choice(letters) for _ in range(length))")
        code_lines.append("            if maybe(0.2):")
        code_lines.append("                name += str(rnd.randint(0, 999))")
        code_lines.append("        return name")
        code_lines.append("")
        code_lines.append("    def quote_ident(name):")
        code_lines.append("        q = rnd.random()")
        code_lines.append("        if q < 0.55:")
        code_lines.append("            return name")
        code_lines.append("        elif q < 0.7:")
        code_lines.append("            return '\"' + name.replace('\"','\"\"') + '\"'")
        code_lines.append("        elif q < 0.85:")
        code_lines.append("            return '`' + name.replace('`','``') + '`'")
        code_lines.append("        else:")
        code_lines.append("            return '[' + name.replace(']','') + ']'")
        code_lines.append("")
        code_lines.append("    def rand_identifier():")
        code_lines.append("        name = rand_ident_base()")
        code_lines.append("        if name.upper() in GRAMMAR_KEYWORDS or maybe(0.2):")
        code_lines.append("            return quote_ident(name)")
        code_lines.append("        return name")
        code_lines.append("")
        code_lines.append("    def rand_table():")
        code_lines.append("        return rand_identifier()")
        code_lines.append("")
        code_lines.append("    def rand_column():")
        code_lines.append("        return rand_identifier()")
        code_lines.append("")
        code_lines.append("    def rand_number():")
        code_lines.append("        return rnd.choice(numeric_constants)")
        code_lines.append("")
        code_lines.append("    def rand_string():")
        code_lines.append("        s = rnd.choice(string_constants)")
        code_lines.append("        # Randomly change quote escaping style sometimes")
        code_lines.append("        return s")
        code_lines.append("")
        code_lines.append("    def rand_const():")
        code_lines.append("        r = rnd.random()")
        code_lines.append("        if r < 0.4: return rand_number()")
        code_lines.append("        if r < 0.8: return rand_string()")
        code_lines.append("        return rnd.choice(bool_null)")
        code_lines.append("")
        code_lines.append("    def rand_func_call(depth):")
        code_lines.append("        fname = rnd.choice(func_names)")
        code_lines.append("        args = []")
        code_lines.append("        n = rnd.randint(0, 3)")
        code_lines.append("        for _ in range(n):")
        code_lines.append("            args.append(rand_expr(depth + 1))")
        code_lines.append("        return mix_case(fname) + '(' + (', '.join(args)) + ')'")
        code_lines.append("")
        code_lines.append("    def rand_paren_expr(depth):")
        code_lines.append("        return '(' + rand_expr(depth + 1) + ')'")
        code_lines.append("")
        code_lines.append("    def rand_case_expr(depth):")
        code_lines.append("        parts = [mix_case('CASE')]")
        code_lines.append("        if maybe(0.3):")
        code_lines.append("            parts.append(rand_expr(depth + 1))")
        code_lines.append("        k = rnd.randint(1, 3)")
        code_lines.append("        for _ in range(k):")
        code_lines.append("            parts.append(mix_case('WHEN'))")
        code_lines.append("            parts.append(rand_expr(depth + 1))")
        code_lines.append("            parts.append(mix_case('THEN'))")
        code_lines.append("            parts.append(rand_expr(depth + 1))")
        code_lines.append("        if maybe(0.5):")
        code_lines.append("            parts.append(mix_case('ELSE'))")
        code_lines.append("            parts.append(rand_expr(depth + 1))")
        code_lines.append("        parts.append(mix_case('END'))")
        code_lines.append("        return ' '.join(parts)")
        code_lines.append("")
        code_lines.append("    def rand_subquery(depth):")
        code_lines.append("        return '(' + build_select_stmt(depth + 1, allow_cte=False, allow_union=False) + ')'")
        code_lines.append("")
        code_lines.append("    def rand_expr(depth=0):")
        code_lines.append("        if depth > 3:")
        code_lines.append("            return rnd.choice([rand_const(), rand_column(), rand_func_call(depth)])")
        code_lines.append("        choice = rnd.random()")
        code_lines.append("        if choice < 0.15:")
        code_lines.append("            return rand_const()")
        code_lines.append("        elif choice < 0.30:")
        code_lines.append("            return rand_column()")
        code_lines.append("        elif choice < 0.45:")
        code_lines.append("            return rand_func_call(depth)")
        code_lines.append("        elif choice < 0.55 and depth < 2 and maybe(0.5):")
        code_lines.append("            return rand_subquery(depth)")
        code_lines.append("        elif choice < 0.7:")
        code_lines.append("            # unary")
        code_lines.append("            op = rnd.choice(['+','-','~', mix_case('NOT')])")
        code_lines.append("            return op + ' ' + rand_expr(depth + 1)")
        code_lines.append("        else:")
        code_lines.append("            # binary")
        code_lines.append("            if maybe(0.6):")
        code_lines.append("                op = rnd.choice(arithmetic_ops)")
        code_lines.append("            else:")
        code_lines.append("                op = rnd.choice(comparison_ops)")
        code_lines.append("            left = rand_expr(depth + 1)")
        code_lines.append("            right = rand_expr(depth + 1)")
        code_lines.append("            if op in ('IN', 'NOT IN') and maybe(0.5):")
        code_lines.append("                # list")
        code_lines.append("                n = rnd.randint(0, 4)")
        code_lines.append("                items = ', '.join(rand_expr(depth + 2) for _ in range(n))")
        code_lines.append("                right = '(' + items + ')'")
        code_lines.append("            return f'{left} {op} {right}'")
        code_lines.append("")
        code_lines.append("    def rand_order_by():")
        code_lines.append("        n = rnd.randint(1, 3)")
        code_lines.append("        items = []")
        code_lines.append("        for _ in range(n):")
        code_lines.append("            expr = rnd.choice([rand_column(), rand_expr(0), str(rnd.randint(1,10))])")
        code_lines.append("            tail = ''")
        code_lines.append("            if maybe(0.5):")
        code_lines.append("                tail += ' ' + mix_case(rnd.choice(['ASC','DESC']))")
        code_lines.append("            if maybe(0.2):")
        code_lines.append("                tail += ' ' + mix_case(rnd.choice(['NULLS FIRST','NULLS LAST']))")
        code_lines.append("            items.append(expr + tail)")
        code_lines.append("        return mix_case('ORDER BY') + ' ' + ', '.join(items)")
        code_lines.append("")
        code_lines.append("    def rand_group_by():")
        code_lines.append("        n = rnd.randint(1, 3)")
        code_lines.append("        items = []")
        code_lines.append("        for _ in range(n):")
        code_lines.append("            items.append(rnd.choice([rand_column(), str(rnd.randint(1,10))]))")
        code_lines.append("        s = mix_case('GROUP BY') + ' ' + ', '.join(items)")
        code_lines.append("        if maybe(0.4):")
        code_lines.append("            s += ' ' + rand_order_by()")
        code_lines.append("        return s")
        code_lines.append("")
        code_lines.append("    def rand_limit():")
        code_lines.append("        parts = [mix_case('LIMIT'), str(rnd.randint(0, 100))]")
        code_lines.append("        if maybe(0.6):")
        code_lines.append("            parts += [mix_case('OFFSET'), str(rnd.randint(0, 50))]")
        code_lines.append("        return ' '.join(parts)")
        code_lines.append("")
        code_lines.append("    def rand_join_clause():")
        code_lines.append("        jt = mix_case(rnd.choice(join_types))")
        code_lines.append("        tbl = rand_table() + ((' ' + mix_case('AS') + ' ' + rand_identifier()) if maybe(0.5) else '')")
        code_lines.append("        if 'NATURAL' in jt.upper():")
        code_lines.append("            return f'{jt} {tbl}'")
        code_lines.append("        if maybe(0.5):")
        code_lines.append("            cond = mix_case('ON') + ' ' + rand_expr(0)")
        code_lines.append("        else:")
        code_lines.append("            cols = ', '.join(rand_column() for _ in range(rnd.randint(1,3)))")
        code_lines.append("            cond = mix_case('USING') + f' ({cols})'")
        code_lines.append("        return f'{jt} {tbl} {cond}'")
        code_lines.append("")
        code_lines.append("    def rand_table_source():")
        code_lines.append("        if maybe(0.2):")
        code_lines.append("            # subquery table source")
        code_lines.append("            return '(' + build_select_stmt(1, allow_cte=False, allow_union=False) + ') ' + mix_case('AS') + ' ' + rand_identifier()")
        code_lines.append("        else:")
        code_lines.append("            return rand_table() + ((' ' + mix_case('AS') + ' ' + rand_identifier()) if maybe(0.5) else '')")
        code_lines.append("")
        code_lines.append("    def build_select_stmt(depth=0, allow_cte=True, allow_union=True):")
        code_lines.append("        parts = []")
        code_lines.append("        if allow_cte and maybe(0.2):")
        code_lines.append("            parts.append(mix_case('WITH') + (' ' + mix_case('RECURSIVE') if maybe(0.2) else ''))")
        code_lines.append("            ncte = rnd.randint(1, 2)")
        code_lines.append("            ctes = []")
        code_lines.append("            for _ in range(ncte):")
        code_lines.append("                name = rand_identifier()")
        code_lines.append("                cols = '(' + ', '.join(rand_identifier() for __ in range(rnd.randint(0,3))) + ')' if maybe(0.5) else ''")
        code_lines.append("                ctes.append(f\"{name} {cols} \" + mix_case('AS') + ' (' + build_select_stmt(depth+1, allow_cte=False, allow_union=False) + ')')")
        code_lines.append("            parts.append(', '.join(ctes))")
        code_lines.append("        parts.append(mix_case('SELECT'))")
        code_lines.append("        if maybe(0.5): parts.append(mix_case(rnd.choice(['DISTINCT','ALL'])))")
        code_lines.append("        ncols = rnd.randint(1, 6)")
        code_lines.append("        col_items = []")
        code_lines.append("        for i in range(ncols):")
        code_lines.append("            if maybe(0.1):")
        code_lines.append("                col_items.append('*')")
        code_lines.append("            else:")
        code_lines.append("                expr = rand_expr(0)")
        code_lines.append("                if maybe(0.5):")
        code_lines.append("                    expr += ' ' + mix_case('AS') + ' ' + rand_identifier()")
        code_lines.append("                col_items.append(expr)")
        code_lines.append("        parts.append(', '.join(col_items))")
        code_lines.append("        if maybe(0.9):")
        code_lines.append("            parts.append(mix_case('FROM'))")
        code_lines.append("            src = rand_table_source()")
        code_lines.append("            parts.append(src)")
        code_lines.append("            nj = rnd.randint(0, 2)")
        code_lines.append("            for _ in range(nj):")
        code_lines.append("                parts.append(rand_join_clause())")
        code_lines.append("        if maybe(0.6):")
        code_lines.append("            parts.append(mix_case('WHERE'))")
        code_lines.append("            parts.append(rand_expr(0))")
        code_lines.append("        if maybe(0.4):")
        code_lines.append("            parts.append(rand_group_by())")
        code_lines.append("            if maybe(0.5):")
        code_lines.append("                parts.append(mix_case('HAVING'))")
        code_lines.append("                parts.append(rand_expr(0))")
        code_lines.append("        if maybe(0.5):")
        code_lines.append("            parts.append(rand_order_by())")
        code_lines.append("        if maybe(0.5):")
        code_lines.append("            parts.append(rand_limit())")
        code_lines.append("        base = ' '.join(parts)")
        code_lines.append("        if allow_union and maybe(0.25):")
        code_lines.append("            k = rnd.randint(1, 2)")
        code_lines.append("            for _ in range(k):")
        code_lines.append("                base += ' ' + mix_case(rnd.choice(['UNION','UNION ALL','INTERSECT','EXCEPT'])) + ' ' + build_select_stmt(depth+1, allow_cte=False, allow_union=False)")
        code_lines.append("        return base")
        code_lines.append("")
        code_lines.append("    def build_insert_stmt():")
        code_lines.append("        parts = [mix_case('INSERT')]")
        code_lines.append("        if maybe(0.3):")
        code_lines.append("            parts += [mix_case('OR'), mix_case(rnd.choice(['REPLACE','ABORT','FAIL','IGNORE','ROLLBACK']))]")
        code_lines.append("        parts += [mix_case('INTO'), rand_table()]")
        code_lines.append("        if maybe(0.6):")
        code_lines.append("            cols = ', '.join(rand_column() for _ in range(rnd.randint(0,5)))")
        code_lines.append("            parts.append('(' + cols + ')')")
        code_lines.append("        if maybe(0.5):")
        code_lines.append("            # VALUES")
        code_lines.append("            nv = rnd.randint(0, 3)")
        code_lines.append("            rows = []")
        code_lines.append("            for _ in range(nv):")
        code_lines.append("                n = rnd.randint(0, 6)")
        code_lines.append("                vals = ', '.join(rand_expr(0) for __ in range(n))")
        code_lines.append("                rows.append('(' + vals + ')')")
        code_lines.append("            if nv == 0 and maybe(0.4):")
        code_lines.append("                parts.append(mix_case('DEFAULT VALUES'))")
        code_lines.append("            else:")
        code_lines.append("                parts.append(mix_case('VALUES'))")
        code_lines.append("                parts.append(', '.join(rows))")
        code_lines.append("        else:")
        code_lines.append("            parts.append(build_select_stmt(0))")
        code_lines.append("        if maybe(0.3):")
        code_lines.append("            parts += [mix_case('ON CONFLICT'), '(' + ', '.join(rand_column() for _ in range(rnd.randint(1,3))) + ')', mix_case('DO'), rnd.choice([mix_case('NOTHING'), mix_case('UPDATE SET') + ' ' + ', '.join(f'{rand_column()}=' + rand_expr(0) for __ in range(rnd.randint(1,3)))])]")
        code_lines.append("        return ' '.join([p for p in parts if p is not None and p != ''])")
        code_lines.append("")
        code_lines.append("    def build_update_stmt():")
        code_lines.append("        parts = [mix_case('UPDATE')]")
        code_lines.append("        if maybe(0.2):")
        code_lines.append("            parts += [mix_case('OR'), mix_case(rnd.choice(['REPLACE','ABORT','FAIL','IGNORE','ROLLBACK']))]")
        code_lines.append("        parts.append(rand_table())")
        code_lines.append("        parts.append(mix_case('SET'))")
        code_lines.append("        n = rnd.randint(1, 6)")
        code_lines.append("        assigns = []")
        code_lines.append("        for _ in range(n):")
        code_lines.append("            assigns.append(f'{rand_column()} = {rand_expr(0)}')")
        code_lines.append("        parts.append(', '.join(assigns))")
        code_lines.append("        if maybe(0.7):")
        code_lines.append("            parts += [mix_case('WHERE'), rand_expr(0)]")
        code_lines.append("        if maybe(0.3):")
        code_lines.append("            parts.append(rand_order_by())")
        code_lines.append("        if maybe(0.3):")
        code_lines.append("            parts.append(rand_limit())")
        code_lines.append("        return ' '.join(parts)")
        code_lines.append("")
        code_lines.append("    def build_delete_stmt():")
        code_lines.append("        parts = [mix_case('DELETE'), mix_case('FROM'), rand_table()]")
        code_lines.append("        if maybe(0.7):")
        code_lines.append("            parts += [mix_case('WHERE'), rand_expr(0)]")
        code_lines.append("        if maybe(0.3):")
        code_lines.append("            parts.append(rand_order_by())")
        code_lines.append("        if maybe(0.3):")
        code_lines.append("            parts.append(rand_limit())")
        code_lines.append("        return ' '.join(parts)")
        code_lines.append("")
        code_lines.append("    def build_create_table_stmt():")
        code_lines.append("        parts = [mix_case('CREATE')]")
        code_lines.append("        if maybe(0.2): parts.append(mix_case('TEMP'))")
        code_lines.append("        parts += [mix_case('TABLE')]")
        code_lines.append("        if maybe(0.5): parts += [mix_case('IF NOT EXISTS')]")
        code_lines.append("        tname = rand_table()")
        code_lines.append("        parts.append(tname)")
        code_lines.append("        ncols = rnd.randint(1, 8)")
        code_lines.append("        cols = []")
        code_lines.append("        for i in range(ncols):")
        code_lines.append("            cname = rand_column()")
        code_lines.append("            ctype = rnd.choice(sql_types) if maybe(0.9) else ''")
        code_lines.append("            cdef = cname + (' ' + ctype if ctype else '')")
        code_lines.append("            # constraints on column")
        code_lines.append("            if maybe(0.5):")
        code_lines.append("                if maybe(0.5):")
        code_lines.append("                    cdef += ' ' + mix_case('PRIMARY KEY')")
        code_lines.append("                    if maybe(0.3): cdef += ' ' + mix_case('AUTOINCREMENT')")
        code_lines.append("                if maybe(0.5):")
        code_lines.append("                    cdef += ' ' + mix_case('NOT NULL')")
        code_lines.append("                if maybe(0.3):")
        code_lines.append("                    cdef += ' ' + mix_case('UNIQUE')")
        code_lines.append("                if maybe(0.4):")
        code_lines.append("                    cdef += ' ' + mix_case('DEFAULT') + ' ' + rnd.choice([rand_const(), mix_case('CURRENT_TIMESTAMP'), mix_case('CURRENT_DATE'), mix_case('CURRENT_TIME')])")
        code_lines.append("                if maybe(0.3):")
        code_lines.append("                    cdef += ' ' + mix_case('CHECK') + ' (' + rand_expr(0) + ')'")
        code_lines.append("            cols.append(cdef)")
        code_lines.append("        # table constraints")
        code_lines.append("        if maybe(0.5):")
        code_lines.append("            # primary key over multiple columns")
        code_lines.append("            kcols = ', '.join(rand_column() for _ in range(rnd.randint(1, min(3, ncols))))")
        code_lines.append("            cols.append(mix_case('PRIMARY KEY') + f' ({kcols})')")
        code_lines.append("        if maybe(0.4):")
        code_lines.append("            ucols = ', '.join(rand_column() for _ in range(rnd.randint(1, min(3, ncols))))")
        code_lines.append("            cols.append(mix_case('UNIQUE') + f' ({ucols})')")
        code_lines.append("        if maybe(0.4):")
        code_lines.append("            cols.append(mix_case('CHECK') + ' (' + rand_expr(0) + ')')")
        code_lines.append("        parts.append('(' + ', '.join(cols) + ')')")
        code_lines.append("        return ' '.join(parts)")
        code_lines.append("")
        code_lines.append("    def build_alter_table_stmt():")
        code_lines.append("        t = rand_table()")
        code_lines.append("        choice = rnd.random()")
        code_lines.append("        if choice < 0.33:")
        code_lines.append("            return f\"{mix_case('ALTER TABLE')} {t} {mix_case('ADD COLUMN')} {rand_column()} {rnd.choice(sql_types)}\"")
        code_lines.append("        elif choice < 0.66:")
        code_lines.append("            return f\"{mix_case('ALTER TABLE')} {t} {mix_case('RENAME TO')} {rand_table()}\"")
        code_lines.append("        else:")
        code_lines.append("            return f\"{mix_case('ALTER TABLE')} {t} {mix_case('ADD')} {mix_case('CONSTRAINT')} {rand_identifier()} {mix_case('CHECK')} ({rand_expr(0)})\"")
        code_lines.append("")
        code_lines.append("    def build_drop_stmt():")
        code_lines.append("        kind = rnd.choice(['TABLE','VIEW','INDEX'])")
        code_lines.append("        parts = [mix_case('DROP'), mix_case(kind)]")
        code_lines.append("        if maybe(0.5): parts += [mix_case('IF EXISTS')]")
        code_lines.append("        parts.append(rand_table())")
        code_lines.append("        return ' '.join(parts)")
        code_lines.append("")
        code_lines.append("    def build_create_index_stmt():")
        code_lines.append("        parts = [mix_case('CREATE')]")
        code_lines.append("        if maybe(0.5): parts.append(mix_case('UNIQUE'))")
        code_lines.append("        parts.append(mix_case('INDEX'))")
        code_lines.append("        if maybe(0.5): parts += [mix_case('IF NOT EXISTS')]")
        code_lines.append("        parts.append(rand_identifier())")
        code_lines.append("        parts += [mix_case('ON'), rand_table()]")
        code_lines.append("        n = rnd.randint(1, 4)")
        code_lines.append("        items = []")
        code_lines.append("        for _ in range(n):")
        code_lines.append("            it = rand_column()")
        code_lines.append("            if maybe(0.5): it += ' ' + mix_case(rnd.choice(['ASC','DESC']))")
        code_lines.append("            items.append(it)")
        code_lines.append("        parts.append('(' + ', '.join(items) + ')')")
        code_lines.append("        if maybe(0.3):")
        code_lines.append("            parts.append(rand_where_clause_for_index())")
        code_lines.append("        return ' '.join(parts)")
        code_lines.append("")
        code_lines.append("    def rand_where_clause_for_index():")
        code_lines.append("        return mix_case('WHERE') + ' ' + rand_expr(0)")
        code_lines.append("")
        code_lines.append("    def build_create_view_stmt():")
        code_lines.append("        parts = [mix_case('CREATE'), mix_case('VIEW')]")
        code_lines.append("        if maybe(0.5): parts += [mix_case('IF NOT EXISTS')]")
        code_lines.append("        parts.append(rand_identifier())")
        code_lines.append("        parts.append(mix_case('AS'))")
        code_lines.append("        parts.append(build_select_stmt(0))")
        code_lines.append("        return ' '.join(parts)")
        code_lines.append("")
        code_lines.append("    def build_txn_stmt():")
        code_lines.append("        return rnd.choice([mix_case('BEGIN'), mix_case('BEGIN TRANSACTION'), mix_case('COMMIT'), mix_case('END'), mix_case('ROLLBACK')])")
        code_lines.append("")
        code_lines.append("    def build_explain_stmt():")
        code_lines.append("        return mix_case('EXPLAIN') + ' ' + build_select_stmt(0)")
        code_lines.append("")
        code_lines.append("    def build_pragma_stmt():")
        code_lines.append("        # For SQLite-like token coverage; parser may treat as identifiers")
        code_lines.append("        name = rand_identifier()")
        code_lines.append("        if maybe(0.5):")
        code_lines.append("            return mix_case('PRAGMA') + ' ' + name + '=' + rnd.choice([rand_number(), rand_string()])")
        code_lines.append("        else:")
        code_lines.append("            return mix_case('PRAGMA') + ' ' + name + '(' + (', '.join([rnd.choice([rand_number(), rand_string()]) for _ in range(rnd.randint(0,2))])) + ')'")
        code_lines.append("")
        code_lines.append("    def build_misc_stmt():")
        code_lines.append("        # Other statements to diversify tokens")
        code_lines.append("        options = []")
        code_lines.append("        options.append(lambda: mix_case('VACUUM'))")
        code_lines.append("        options.append(lambda: mix_case('ANALYZE'))")
        code_lines.append("        options.append(lambda: mix_case('REINDEX') + ' ' + rand_identifier())")
        code_lines.append("        options.append(build_explain_stmt)")
        code_lines.append("        options.append(build_pragma_stmt)")
        code_lines.append("        return rnd.choice(options)()")
        code_lines.append("")
        code_lines.append("    def sprinkle_comments(sql):")
        code_lines.append("        if len(sql) < 8:")
        code_lines.append("            return sql")
        code_lines.append("        # Insert a comment at some whitespace positions")
        code_lines.append("        idxs = [i for i, ch in enumerate(sql) if ch == ' ']")
        code_lines.append("        if not idxs:")
        code_lines.append("            return sql")
        code_lines.append("        n = min(len(idxs), rnd.randint(1, 2))")
        code_lines.append("        comment_variants = [")
        code_lines.append("            '/*c*/', '/** comment **/', '/*1*/', '-- line\\n', '--x\\r\\n'")
        code_lines.append("        ]")
        code_lines.append("        s = list(sql)")
        code_lines.append("        # Insert from right to avoid shifting earlier indices")
        code_lines.append("        for pos in sorted(rndsamp(idxs, n), reverse=True):")
        code_lines.append("            comm = rnd.choice(comment_variants)")
        code_lines.append("            s[pos] = ' ' + comm + ' '")
        code_lines.append("        return ''.join(s)")
        code_lines.append("")
        code_lines.append("    def rndsamp(seq, k):")
        code_lines.append("        if k <= 0:")
        code_lines.append("            return []")
        code_lines.append("        if k >= len(seq):")
        code_lines.append("            return list(seq)")
        code_lines.append("        return rnd.sample(seq, k)")
        code_lines.append("")
        code_lines.append("    def random_noise_statement():")
        code_lines.append("        # Generate token soup from grammar literals/keywords and identifiers.")
        code_lines.append("        toks = []")
        code_lines.append("        max_len = rnd.randint(3, 20)")
        code_lines.append("        pool = []")
        code_lines.append("        pool += [mix_case(k) for k in list(GRAMMAR_KEYWORDS)[:200]]")
        code_lines.append("        pool += list(GRAMMAR_LITERALS)[:200]")
        code_lines.append("        pool += ['(',')',',',';','*','/','+','-','%','=',':','::','||','|','&','^','!','!=','<>','<=','>=','<','>','.', '..']")
        code_lines.append("        if not pool:")
        code_lines.append("            pool = ['SELECT','FROM','WHERE','INSERT','INTO','VALUES','UPDATE','SET','DELETE','CREATE','TABLE','INDEX','VIEW','DROP','ALTER',';','(',')',',','*','=','+','-','/']")
        code_lines.append("        for _ in range(max_len):")
        code_lines.append("            r = rnd.random()")
        code_lines.append("            if r < 0.25:")
        code_lines.append("                toks.append(rand_identifier())")
        code_lines.append("            elif r < 0.5:")
        code_lines.append("                toks.append(rnd.choice([rand_number(), rand_string(), rnd.choice(['TRUE','FALSE','NULL'])]))")
        code_lines.append("            else:")
        code_lines.append("                toks.append(rnd.choice(pool))")
        code_lines.append("        s = ' '.join(toks)")
        code_lines.append("        if maybe(0.3): s = sprinkle_comments(s)")
        code_lines.append("        return s")
        code_lines.append("")
        code_lines.append("    def maybe_semicolon(sql):")
        code_lines.append("        if maybe(0.6):")
        code_lines.append("            # 60% end with semicolon, sometimes multiple")
        code_lines.append("            return sql + (';' * rnd.randint(1, 2))")
        code_lines.append("        return sql")
        code_lines.append("")
        code_lines.append("    statements = []")
        code_lines.append("    # Deterministic base seeds")
        code_lines.append("    base_examples = [")
        code_lines.append("        'SELECT 1',")
        code_lines.append("        'SELECT * FROM t',")
        code_lines.append("        'SELECT id, name FROM users WHERE id = 1',")
        code_lines.append("        'INSERT INTO t VALUES (1)',")
        code_lines.append("        'UPDATE t SET x=1 WHERE y=2',")
        code_lines.append("        'DELETE FROM t WHERE x < 0',")
        code_lines.append("        'CREATE TABLE t (id INT PRIMARY KEY, name TEXT)',")
        code_lines.append("        'DROP TABLE IF EXISTS t',")
        code_lines.append("        'BEGIN', 'COMMIT'")
        code_lines.append("    ]")
        code_lines.append("    statements += base_examples")
        code_lines.append("")
        code_lines.append("    # Generate a balanced corpus")
        code_lines.append("    n_select = 600")
        code_lines.append("    n_insert = 220")
        code_lines.append("    n_update = 180")
        code_lines.append("    n_delete = 180")
        code_lines.append("    n_create_tbl = 180")
        code_lines.append("    n_alter_tbl = 100")
        code_lines.append("    n_drop = 120")
        code_lines.append("    n_index = 100")
        code_lines.append("    n_view = 60")
        code_lines.append("    n_txn = 80")
        code_lines.append("    n_misc = 60")
        code_lines.append("    n_noise = 240")
        code_lines.append("")
        code_lines.append("    for _ in range(n_select):")
        code_lines.append("        s = build_select_stmt(0)")
        code_lines.append("        if maybe(0.1): s = sprinkle_comments(s)")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    for _ in range(n_insert):")
        code_lines.append("        s = build_insert_stmt()")
        code_lines.append("        if maybe(0.1): s = sprinkle_comments(s)")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    for _ in range(n_update):")
        code_lines.append("        s = build_update_stmt()")
        code_lines.append("        if maybe(0.1): s = sprinkle_comments(s)")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    for _ in range(n_delete):")
        code_lines.append("        s = build_delete_stmt()")
        code_lines.append("        if maybe(0.1): s = sprinkle_comments(s)")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    for _ in range(n_create_tbl):")
        code_lines.append("        s = build_create_table_stmt()")
        code_lines.append("        if maybe(0.05): s = sprinkle_comments(s)")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    for _ in range(n_alter_tbl):")
        code_lines.append("        s = build_alter_table_stmt()")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    for _ in range(n_drop):")
        code_lines.append("        s = build_drop_stmt()")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    for _ in range(n_index):")
        code_lines.append("        s = build_create_index_stmt()")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    for _ in range(n_view):")
        code_lines.append("        s = build_create_view_stmt()")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    for _ in range(n_txn):")
        code_lines.append("        s = build_txn_stmt()")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    for _ in range(n_misc):")
        code_lines.append("        s = build_misc_stmt()")
        code_lines.append("        statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    # Tokenizer/grammar stress: noise and corner-case expressions in SELECT 1 style")
        code_lines.append("    for _ in range(n_noise):")
        code_lines.append("        if maybe(0.5):")
        code_lines.append("            statements.append(maybe_semicolon(random_noise_statement()))")
        code_lines.append("        else:")
        code_lines.append("            # SELECT with exotic constants and operators")
        code_lines.append("            exprs = []")
        code_lines.append("            k = rnd.randint(1, 5)")
        code_lines.append("            for __ in range(k):")
        code_lines.append("                e = rnd.choice([rand_const(), rand_expr(0)])")
        code_lines.append("                if maybe(0.4):")
        code_lines.append("                    e = '(' * rnd.randint(0,2) + e + ')' * rnd.randint(0,2)")
        code_lines.append("                exprs.append(e)")
        code_lines.append("            s = mix_case('SELECT') + ' ' + ', '.join(exprs)")
        code_lines.append("            if maybe(0.6):")
        code_lines.append("                s += ' ' + mix_case('FROM') + ' ' + rand_table()")
        code_lines.append("            if maybe(0.5):")
        code_lines.append("                s += ' ' + mix_case('WHERE') + ' ' + rand_expr(0)")
        code_lines.append("            statements.append(maybe_semicolon(s))")
        code_lines.append("")
        code_lines.append("    # Deduplicate a bit to save time if accidentally too many duplicates")
        code_lines.append("    # But keep order roughly; use set on slices for speed control if needed.")
        code_lines.append("    # We will keep as-is to avoid overhead.")
        code_lines.append("")
        code_lines.append("    # Execute in a single parse_sql call to maximize efficiency bonus")
        code_lines.append("    parse_sql(statements)")
        code_lines.append("    RUN_DONE = True")
        code_lines.append("    return False")
        code = "\n".join(code_lines)
        return {"code": code}