import os
from typing import List

class Solution:
    def solve(self, resources_path: str) -> List[str]:
        sql_tests = [
            "SELECT * FROM users;",
            "SELECT name, age FROM users WHERE age > 18;",
            "SELECT COUNT(*) FROM users;",
            "SELECT COUNT(DISTINCT name) FROM users;",
            "INSERT INTO users (name, age) VALUES ('Alice', 25);",
            "INSERT INTO users (name, age) VALUES ('Bob', 30), ('Charlie', 22);",
            "UPDATE users SET age = age + 1 WHERE name = 'Alice';",
            "UPDATE users SET name = 'Alicia' WHERE age > 25;",
            "DELETE FROM users WHERE age < 18;",
            "DELETE FROM users WHERE name IN ('Alice', 'Bob');",
            "SELECT u.name, o.product FROM users u INNER JOIN orders o ON u.id = o.user_id;",
            "SELECT u.name, o.product FROM users u LEFT JOIN orders o ON u.id = o.user_id;",
            "SELECT u.name, o.product FROM users u RIGHT JOIN orders o ON u.id = o.user_id;",
            "SELECT * FROM users FULL OUTER JOIN orders ON users.id = orders.user_id;",
            "SELECT * FROM users CROSS JOIN products;",
            "SELECT * FROM users WHERE id IN (SELECT user_id FROM orders);",
            "SELECT * FROM users WHERE EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id);",
            "SELECT * FROM users WHERE NOT EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id);",
            "SELECT name FROM users GROUP BY name;",
            "SELECT name, COUNT(*) FROM users GROUP BY name HAVING COUNT(*) > 1;",
            "SELECT * FROM users ORDER BY age ASC;",
            "SELECT * FROM users ORDER BY age DESC, name ASC;",
            "SELECT * FROM users LIMIT 10;",
            "SELECT * FROM users OFFSET 5 LIMIT 10;",
            "CREATE TABLE test_table (id INTEGER PRIMARY KEY, name VARCHAR(50), age INTEGER);",
            "CREATE TABLE test_table (id INTEGER, name VARCHAR(50), age INTEGER, CONSTRAINT pk_id PRIMARY KEY (id));",
            "DROP TABLE test_table;",
            "ALTER TABLE users ADD COLUMN email VARCHAR(100);",
            "ALTER TABLE users DROP COLUMN email;",
            "CREATE INDEX idx_users_name ON users (name);",
            "DROP INDEX idx_users_name;",
            "SELECT 'hello world', 123, 45.67, NULL FROM dual;",
            "SELECT 'O''Reilly', \"Wilson's\" FROM dual;",
            "SELECT * FROM users WHERE name LIKE 'A%';",
            "SELECT * FROM users WHERE name LIKE '%son' ESCAPE '!';",
            "SELECT * FROM users WHERE age BETWEEN 18 AND 65;",
            "SELECT * FROM users WHERE age NOT BETWEEN 18 AND 65;",
            "SELECT * FROM users WHERE name IS NULL;",
            "SELECT * FROM users WHERE name IS NOT NULL;",
            "SELECT CASE WHEN age > 18 THEN 'adult' ELSE 'minor' END AS status FROM users;",
            "SELECT CASE age WHEN 18 THEN 'young' WHEN 65 THEN 'senior' ELSE 'middle' END FROM users;",
            "SELECT name || ' ' || surname AS full_name FROM users;",
            "SELECT age * 2 + 10 AS doubled_plus_ten FROM users;",
            "SELECT SUM(age), AVG(age), MAX(age), MIN(age) FROM users;",
            "SELECT CURRENT_DATE;",
            "SELECT CURRENT_TIME;",
            "SELECT CURRENT_TIMESTAMP;",
            "SELECT EXTRACT(YEAR FROM CURRENT_DATE) AS year;",
            "SELECT * FROM users WHERE (age > 18 OR name = 'admin') AND active = TRUE;",
            "SELECT * FROM users UNION SELECT * FROM customers;",
            "SELECT * FROM users UNION ALL SELECT * FROM customers;",
            "SELECT (SELECT COUNT(*) FROM orders) AS total_orders FROM users LIMIT 1;",
            "SELECT name FROM users WHERE age > ALL (SELECT age FROM children);",
            "SELECT name FROM users WHERE age > ANY (SELECT age FROM children);",
            "WITH user_counts AS (SELECT user_id, COUNT(*) AS order_count FROM orders GROUP BY user_id) SELECT u.name, uc.order_count FROM users u JOIN user_counts uc ON u.id = uc.user_id;",
            "SELECT * FROM users FETCH FIRST 5 ROWS ONLY;",
            "TRUNCATE TABLE users;"
        ]
        return sql_tests